package kopr;

import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

public class Form extends javax.swing.JFrame {

    private int pocetSoketov = -1;
    private final SwingWorker<Void, Integer> worker;
    private int velkostSuboru;
    int sucet = 0;
    private int progress = 0;
    Priebeh priebeh;

    public Form(boolean prerusenie, int poslane, Priebeh priebeh) {
        initComponents();
        this.priebeh = priebeh;
        progress = poslane;
        if(prerusenie){
            startButton.setEnabled(false);            
        }else{
            pokracujButton.setEnabled(false);
        }
        worker = new SwingWorker<Void, Integer>() {
            @Override
            protected Void doInBackground() throws Exception {               
                SwingUtilities.invokeAndWait(() -> {
                    velkostSuboru = Client.komunikacia(pocetSoketov);
                });
                ProgressBar.setMinimum(0);
                ProgressBar.setMaximum(velkostSuboru);
                ProgressBar.setValue(progress);
                priebeh.zvysPriebeh(progress);
                SwingUtilities.invokeLater(() -> {
                    Client.prenos();
                });
                
                while (sucet < velkostSuboru) {
                    sucet = priebeh.dajPriebeh();
                    publish(sucet);                   
                }

                return null;
            }

            @Override
            protected void process(List<Integer> list) {
                ProgressBar.setValue(list.get(list.size() - 1));

            }

            @Override
            protected void done() {               
                ProgressBar.setValue(velkostSuboru);
            }                                  
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pocetSoketovLabel = new javax.swing.JLabel();
        pocetSoketovTextField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        stopButton = new javax.swing.JButton();
        pauzaButton = new javax.swing.JButton();
        pokracujButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pocetSoketovLabel.setText("Pocet Soketov : ");

        startButton.setText("Začni");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        pauzaButton.setText("Preruš");
        pauzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauzaButtonActionPerformed(evt);
            }
        });

        pokracujButton.setText("Pokračuj");
        pokracujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokracujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pauzaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pocetSoketovLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pocetSoketovTextField)
                            .addComponent(stopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pokracujButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocetSoketovLabel)
                    .addComponent(pocetSoketovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauzaButton)
                    .addComponent(pokracujButton))
                .addGap(24, 24, 24)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (pocetSoketovTextField.getText() != null) {
            pocetSoketov = Integer.parseInt(pocetSoketovTextField.getText());
            worker.execute();           
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        try {
            Client.stop();
        } catch (InterruptedException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void pauzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauzaButtonActionPerformed
        try {
            Client.pauza();
        } catch (InterruptedException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pauzaButtonActionPerformed

    private void pokracujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokracujButtonActionPerformed
       worker.execute();       
    }//GEN-LAST:event_pokracujButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton pauzaButton;
    private javax.swing.JLabel pocetSoketovLabel;
    private javax.swing.JTextField pocetSoketovTextField;
    private javax.swing.JButton pokracujButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
